version: '3.8'

services:

    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./nginx/laravel.conf:/etc/nginx/conf.d/laravel.conf
            - ./nginx/ssl:/etc/nginx/ssl
            - ./laravel:/var/www/html
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - app
            - mongo
        networks:
            - app-network

    app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        container_name: laravel_api
        volumes:
            - ./:/var/www/html
        expose:
            - "9000"
        environment:
            - PUID=1000
            - PGID=1000
        networks:
            - app-network
    horizon:
        build:
            context: ./
            dockerfile: ./Dockerfile-horizon
        container_name: laravel_horizon
        volumes:
            - ./:/var/www/html
        depends_on:
            - redis
        command: php artisan horizon
        networks:
            - app-network

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        depends_on:
            - postgres
        networks:
            - app-network

    postgres:
        image: postgres:15
        container_name: postgres
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app-network

    mongo:
        image: mongo:latest
        container_name: mongo
        hostname: mongodb
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        volumes:
            - mongodb-data:/data/db/
            - mongodb-log:/var/log/mongodb/
        env_file:
            - .env
        networks:
            - app-network

    mongo-express:
        image: mongo-express:latest
        container_name: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_SERVER: 'mongodb'
            ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
            ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
            #ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
        depends_on:
            - mongo
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
        name: app-network

volumes:
    postgres_data:
    mongodb-data:
        driver: local
        name: mongo-data
    mongodb-log:
        driver: local
        name: mongo-log
    redis_data:
